/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedOrgRouteRouteImport } from './routes/_authenticated/_org/route'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/_student'
import { Route as AuthenticatedEvaluationsRouteImport } from './routes/_authenticated/evaluations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/_admin/organizations'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/_admin/system'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedStudentCertificatesRouteImport } from './routes/_authenticated/_student/certificates'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated/_student/dashboard'
import { Route as AuthenticatedStudentMyEventsRouteImport } from './routes/_authenticated/_student/my-events'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedOrgOrgDashboardRouteImport } from './routes/_authenticated/_org/org/dashboard'
import { Route as AuthenticatedOrgOrgEventsEventIdRouteImport } from './routes/_authenticated/_org/org/events/$eventId'
import { Route as AuthenticatedOrgOrgEventsNewRouteImport } from './routes/_authenticated/_org/org/events/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrgRouteRoute = AuthenticatedOrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaluationsRoute =
  AuthenticatedEvaluationsRouteImport.update({
    id: '/evaluations',
    path: '/evaluations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedStudentCertificatesRoute =
  AuthenticatedStudentCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentMyEventsRoute =
  AuthenticatedStudentMyEventsRouteImport.update({
    id: '/my-events',
    path: '/my-events',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgOrgDashboardRoute =
  AuthenticatedOrgOrgDashboardRouteImport.update({
    id: '/org/dashboard',
    path: '/org/dashboard',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgOrgEventsEventIdRoute =
  AuthenticatedOrgOrgEventsEventIdRouteImport.update({
    id: '/org/events/$eventId',
    path: '/org/events/$eventId',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgOrgEventsNewRoute =
  AuthenticatedOrgOrgEventsNewRouteImport.update({
    id: '/org/events/new',
    path: '/org/events/new',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/system': typeof AuthenticatedAdminSystemRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/my-events': typeof AuthenticatedStudentMyEventsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/org/dashboard': typeof AuthenticatedOrgOrgDashboardRoute
  '/org/events/$eventId': typeof AuthenticatedOrgOrgEventsEventIdRoute
  '/org/events/new': typeof AuthenticatedOrgOrgEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/evaluations': typeof AuthenticatedEvaluationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/system': typeof AuthenticatedAdminSystemRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/my-events': typeof AuthenticatedStudentMyEventsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/org/dashboard': typeof AuthenticatedOrgOrgDashboardRoute
  '/org/events/$eventId': typeof AuthenticatedOrgOrgEventsEventIdRoute
  '/org/events/new': typeof AuthenticatedOrgOrgEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_org': typeof AuthenticatedOrgRouteRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/evaluations': typeof AuthenticatedEvaluationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/_admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/_admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/_student/certificates': typeof AuthenticatedStudentCertificatesRoute
  '/_authenticated/_student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/_student/my-events': typeof AuthenticatedStudentMyEventsRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/_org/org/dashboard': typeof AuthenticatedOrgOrgDashboardRoute
  '/_authenticated/_org/org/events/$eventId': typeof AuthenticatedOrgOrgEventsEventIdRoute
  '/_authenticated/_org/org/events/new': typeof AuthenticatedOrgOrgEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/evaluations'
    | '/profile'
    | '/reports'
    | '/organizations'
    | '/system'
    | '/users'
    | '/certificates'
    | '/dashboard'
    | '/my-events'
    | '/events/$eventId'
    | '/events/'
    | '/org/dashboard'
    | '/org/events/$eventId'
    | '/org/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/evaluations'
    | '/profile'
    | '/reports'
    | '/organizations'
    | '/system'
    | '/users'
    | '/certificates'
    | '/dashboard'
    | '/my-events'
    | '/events/$eventId'
    | '/events'
    | '/org/dashboard'
    | '/org/events/$eventId'
    | '/org/events/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_org'
    | '/_authenticated/_admin'
    | '/_authenticated/_student'
    | '/_authenticated/evaluations'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/_admin/organizations'
    | '/_authenticated/_admin/system'
    | '/_authenticated/_admin/users'
    | '/_authenticated/_student/certificates'
    | '/_authenticated/_student/dashboard'
    | '/_authenticated/_student/my-events'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/events/'
    | '/_authenticated/_org/org/dashboard'
    | '/_authenticated/_org/org/events/$eventId'
    | '/_authenticated/_org/org/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_org': {
      id: '/_authenticated/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrgRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluations': {
      id: '/_authenticated/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof AuthenticatedEvaluationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/organizations': {
      id: '/_authenticated/_admin/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/system': {
      id: '/_authenticated/_admin/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_student/certificates': {
      id: '/_authenticated/_student/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedStudentCertificatesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/dashboard': {
      id: '/_authenticated/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/my-events': {
      id: '/_authenticated/_student/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof AuthenticatedStudentMyEventsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_org/org/dashboard': {
      id: '/_authenticated/_org/org/dashboard'
      path: '/org/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgOrgDashboardRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/org/events/$eventId': {
      id: '/_authenticated/_org/org/events/$eventId'
      path: '/org/events/$eventId'
      fullPath: '/org/events/$eventId'
      preLoaderRoute: typeof AuthenticatedOrgOrgEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/org/events/new': {
      id: '/_authenticated/_org/org/events/new'
      path: '/org/events/new'
      fullPath: '/org/events/new'
      preLoaderRoute: typeof AuthenticatedOrgOrgEventsNewRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
  }
}

interface AuthenticatedOrgRouteRouteChildren {
  AuthenticatedOrgOrgDashboardRoute: typeof AuthenticatedOrgOrgDashboardRoute
  AuthenticatedOrgOrgEventsEventIdRoute: typeof AuthenticatedOrgOrgEventsEventIdRoute
  AuthenticatedOrgOrgEventsNewRoute: typeof AuthenticatedOrgOrgEventsNewRoute
}

const AuthenticatedOrgRouteRouteChildren: AuthenticatedOrgRouteRouteChildren = {
  AuthenticatedOrgOrgDashboardRoute: AuthenticatedOrgOrgDashboardRoute,
  AuthenticatedOrgOrgEventsEventIdRoute: AuthenticatedOrgOrgEventsEventIdRoute,
  AuthenticatedOrgOrgEventsNewRoute: AuthenticatedOrgOrgEventsNewRoute,
}

const AuthenticatedOrgRouteRouteWithChildren =
  AuthenticatedOrgRouteRoute._addFileChildren(
    AuthenticatedOrgRouteRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentCertificatesRoute: typeof AuthenticatedStudentCertificatesRoute
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentMyEventsRoute: typeof AuthenticatedStudentMyEventsRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentCertificatesRoute: AuthenticatedStudentCertificatesRoute,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentMyEventsRoute: AuthenticatedStudentMyEventsRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgRouteRoute: typeof AuthenticatedOrgRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedEvaluationsRoute: typeof AuthenticatedEvaluationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgRouteRoute: AuthenticatedOrgRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedEvaluationsRoute: AuthenticatedEvaluationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
